services:
  postgres_a:
    image: postgres:16
    container_name: mvcc_postgres_a
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mvcc_wiki
    ports:
      - "5433:5432"
    volumes:
      - pgdata_a:/var/lib/postgresql/data

  postgres_b:
    image: postgres:16
    container_name: mvcc_postgres_b
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mvcc_wiki
    ports:
      - "5434:5432"
    volumes:
      - pgdata_b:/var/lib/postgresql/data

volumes:
  pgdata_a:
  pgdata_b: